### ISSUE TITLE
remove redundancy of 'data' and 'Data' directories

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/shiny-leaflet#2]
I don't think there's a reason we have both, and it's confusing. I think we simply want to remove one and make sure all the .R files refer to the remaining one. But I could be mistaken.

The one difference between 'data' and 'Data' I see is that there is a Shiny-App/data/zips/pdf but not a Shiny-App/Data/zips/pdf

**Comment by SimonGoring** [comment]
It's a frustrating problem, probably worse because I use windows :)

This is now resolved in commit https://github.com/PalEON-Project/shiny-leaflet/commit/1ee5494966772ddbdefd4bc42adef3316fcfbce3

The issue was that the Windows machine didn't see a difference between `Data` and `data` directories, so I only had one directory locally (the `data` directory), but the `git push` didn't resolve the problem by collapsing the two directories into one.

By renaming (to `data_something`), pushing, pulling, renaming again (back to `data`) and then pushing, I got it cleaned up.

Ridiculous.  Windows, more like Windoze, am I right?!
